/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author developer
 */

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.internal.LinkedTreeMap;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import jdk.nashorn.internal.parser.JSONParser;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hostnameTextField = new javax.swing.JTextField();
        port_wsSpinner = new javax.swing.JSpinner();
        clientportSpinner = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        debugCheckBox = new javax.swing.JCheckBox();
        botdelaySpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        intervaltickerupdateSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        periodstoragetickerSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        timeoutbuySpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        timeoutsellSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tvgainSpinner = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        tvtradinglimitbuySpinner = new javax.swing.JSpinner();
        tvpyramidCheckBox = new javax.swing.JCheckBox();
        tvtradinglimitsellSpinner = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        tvprotectionCheckBox = new javax.swing.JCheckBox();
        retrytvorderCheckBox = new javax.swing.JCheckBox();
        verboseCheckBox = new javax.swing.JCheckBox();
        watchmodeCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        exchangesTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pairsTree = new javax.swing.JTree();
        jPanel6 = new javax.swing.JPanel();
        enabledCheckBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        authorizedfromsTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        hostTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        port_imaglistenerSpinner = new javax.swing.JSpinner();
        tlsCheckBox = new javax.swing.JCheckBox();
        rejectunauthorizedCheckBox = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        strategiesTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        boughtpriceTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JSON Editor");
        setResizable(false);

        jLabel1.setText("port:");

        jLabel2.setText("clientport:");

        jLabel3.setText("hostname:");

        hostnameTextField.setText("127.0.0.1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hostnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(port_wsSpinner)
                    .addComponent(clientportSpinner))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(port_wsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientportSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hostnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ws", jPanel2);

        debugCheckBox.setText("debug");

        jLabel4.setText("BOT_DELAY:");

        jLabel5.setText("interval_ticker_update:");

        jLabel6.setText("period_storage_ticker:");

        jLabel7.setText("timeout_buy:");

        jLabel8.setText("timeout_sell:");

        jLabel9.setText("TV_GAIN:");

        tvgainSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.1f));

        jLabel10.setText("TV_TRADING_LIMIT_BUY:");

        tvtradinglimitbuySpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.001f));

        tvpyramidCheckBox.setText("TV_PYRAMID");

        tvtradinglimitsellSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.001f));

        jLabel11.setText("TV_TRADING_LIMIT_SELL:");

        tvprotectionCheckBox.setText("TV_PROTECTION");

        retrytvorderCheckBox.setText("RETRY_TV_ORDER");

        verboseCheckBox.setText("VERBOSE");

        watchmodeCheckBox.setText("WATCH_MODE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tvtradinglimitbuySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tvtradinglimitsellSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botdelaySpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(intervaltickerupdateSpinner)
                            .addComponent(periodstoragetickerSpinner)
                            .addComponent(timeoutbuySpinner)
                            .addComponent(timeoutsellSpinner)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39)
                        .addComponent(tvgainSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tvprotectionCheckBox)
                    .addComponent(retrytvorderCheckBox)
                    .addComponent(watchmodeCheckBox)
                    .addComponent(debugCheckBox)
                    .addComponent(tvpyramidCheckBox)
                    .addComponent(verboseCheckBox))
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botdelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(debugCheckBox))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervaltickerupdateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tvpyramidCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(periodstoragetickerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvprotectionCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(timeoutbuySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrytvorderCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(timeoutsellSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verboseCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tvgainSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchmodeCheckBox))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tvtradinglimitbuySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tvtradinglimitsellSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("bot", jPanel3);

        exchangesTable.setAutoCreateRowSorter(true);
        exchangesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"bittrex", "YOUR_API_KEY_HERE", "YOUR_SECRET_KEY_HERE"},
                {"cryptopia", "YOUR_API_KEY_HERE", "YOUR_SECRET_KEY_HERE"},
                {"kraken", "YOUR_API_KEY_HERE", "YOUR_SECRET_KEY_HERE"},
                {"poloniex", "YOUR_API_KEY_HERE", "YOUR_SECRET_KEY_HERE"}
            },
            new String [] {
                "Name", "key", "secret"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exchangesTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(exchangesTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("exchanges", jPanel4);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("pairs");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("bittrex");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-LTC");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-ETH");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-XRP");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("poloniex");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-LTC");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-ETH");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-XRP");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("kraken");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-LTC");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-ETH");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-XRP");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("cryptopia");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-LTC");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-ETH");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTC-XRP");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("strategy:bb");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        pairsTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        pairsTree.setEditable(true);
        pairsTree.setRootVisible(false);
        jScrollPane4.setViewportView(pairsTree);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("pairs", jPanel5);

        enabledCheckBox.setText("enabled");

        jLabel12.setText("authorized_froms:");

        authorizedfromsTextField.setText("[\"noreply@tradingview.com\"]");

        jLabel13.setText("user:");

        userTextField.setText("YOUR_EMAIL_HERE");

        jLabel14.setText("password:");

        passwordTextField.setText("YOUR_PASSWORD_HERE");

        jLabel15.setText("host:");

        hostTextField.setText("imap.gmail.com");

        jLabel16.setText("port:");

        tlsCheckBox.setText("tls");

        rejectunauthorizedCheckBox.setText("rejectUnauthorized");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enabledCheckBox)
                    .addComponent(port_imaglistenerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(tlsCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                            .addComponent(rejectunauthorizedCheckBox))
                        .addComponent(authorizedfromsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hostTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(enabledCheckBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(authorizedfromsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(port_imaglistenerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlsCheckBox)
                    .addComponent(rejectunauthorizedCheckBox))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("imag_listener", jPanel6);

        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        strategiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"bb",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678),  new Boolean(false), null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"gain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"pp",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"strepgain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"bbgain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"gainbb",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"bbstepgain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"stepgainbb",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"bbpp",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"ppbb",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"gainstepgain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"stepgaingain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"gainpp",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"ppgain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"stepgainpp",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)},
                {"ppstepgain",  new Double(0.001),  new Double(15.0),  new Double(0.1),  new Double(0.6),  new Double(16.0),  new Double(8.0),  new Double(40.0),  new Double(40.0),  new Double(2.0),  new Double(50.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(0.6),  new Double(2.0),  new Double(70.0),  new Double(2.0),  new Double(2.0),  new Double(5.0),  new Double(250.0),  new Double(1.0E-8),  new Double(1.0E-8),  new Double(0.12345678), null, null,  new Double(60.0),  new Boolean(true),  new Double(1.0E-4),  new Double(1.0E-4)}
            },
            new String [] {
                "Name", "TRADING_LIMIT", "PERIOD", "BUY_LEVEL", "GAIN", "EMA1", "EMA2", "HIGH_BB", "LOW_BB", "STDV", "SMAPERIOD", "BUYLVL1", "BUYLVL2", "BUYLVL3", "SELLLVL1", "SELLLVL2", "SELLLVL3", "BUYLVL", "SELLLVL", "LASTPOINTS", "AVGPOINTS", "AVGMINIMUM", "PP_BUY", "PP_SELL", "PANIC_SELL", "DOUBLE_UP", "STOP_LIMIT", "BUY_ENABLE", "MIN_VOLUME_TO_BUY", "MIN_VOLUME_TO_SELL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        strategiesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(strategiesTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("strategies", jPanel7);

        jLabel17.setText("BOUGHT_PRICE:");

        boughtpriceTextField.setText("0.104744");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel17)
                .addGap(45, 45, 45)
                .addComponent(boughtpriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(boughtpriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("optionals", jPanel1);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
                System.out.println(mainFrame.getJsonString());
                mainFrame.readJSON(mainFrame.getJsonString());
                mainFrame.readFile();
            }
        });
    }

    public void readFile() {
        String content;
        try {
            content = new String(Files.readAllBytes(Paths.get("config.js")));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error occurred while import config.js");
            return;
        }
        HashMap<String, Object> contentMap = readJSON(content);
        
        if (contentMap.containsKey("ws")) {
            setMap_ws((LinkedTreeMap<String, Object>) contentMap.get("ws"));
        }
    
        if (contentMap.containsKey("bot")) {
            setMap_bot((LinkedTreeMap<String, Object>)contentMap.get("bot"));
        }
        
        if (contentMap.containsKey("exchanges")) {
            setMap_exchanges((LinkedTreeMap<String, Object>)contentMap.get("exchanges"));
        }
        
        if (contentMap.containsKey("pairs")) {
            setMap_pairs((LinkedTreeMap<String, Object>)contentMap.get("pairs"));
        }
        
        if (contentMap.containsKey("imap_listener")) {
            setMap_imap_listener((LinkedTreeMap<String, Object>)contentMap.get("imap_listener"));
        }
        
        if (contentMap.containsKey("strategies")) {
            setMap_strategies((LinkedTreeMap<String, Object>)contentMap.get("strategies"));
        }
        
        if (contentMap.containsKey("optionals")) {
            setMap_optionals((LinkedTreeMap<String, Object>)contentMap.get("optionals"));
        }
    }
    
    public void saveFile() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text File(*.js,*.json,*.txt)", "js", "json", "txt");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filename = chooser.getSelectedFile().getPath();
            try (BufferedWriter out = new BufferedWriter(new FileWriter(filename))) {
                out.write(getJsonString());
            }
            catch (IOException e) {

            }
        }
    }
    
    ////////////////////////////////////////////////////////////////////////////
    
    public String getJsonString() {
        Gson gsonObj = new Gson();
        String jsonString = gsonObj.toJson(getMap());
        return jsonString;
    }
    
    public HashMap<String, Object> getMap() {
        HashMap<String, Object> resultMap = new HashMap<>();
        
        resultMap.put("ws", getMap_ws());
        resultMap.put("bot", getMap_bot());
        resultMap.put("exchanges", getMap_exchanges());
        resultMap.put("pairs", getMap_pairs());
        resultMap.put("imap_listener", getMap_imap_listener());
        resultMap.put("strategies", getMap_strategies());
        resultMap.put("optionals", getMap_optioanal());
        
        return resultMap;
    }
    
    public HashMap<String, Object> getMap_ws() {
        HashMap<String, Object> wsMap = new HashMap<>();
        
        wsMap.put("port", port_wsSpinner.getValue());
        wsMap.put("clientport", clientportSpinner.getValue());
        wsMap.put("hostname", hostnameTextField.getText());
        
        return wsMap;
    }
    
    public void setMap_ws(LinkedTreeMap<String, Object> wsMap) {
        if (wsMap.containsKey("port")) {
            port_wsSpinner.setValue(wsMap.get("port"));
        }
        if (wsMap.containsKey("clientport")) {
            clientportSpinner.setValue(wsMap.get("clientport"));
        }
        if (wsMap.containsKey("hostname")) {
            hostnameTextField.setText((String)wsMap.get("hostname"));
        }
    }
    
    public HashMap<String, Object> getMap_bot() {
        HashMap<String, Object> botMap = new HashMap<>();
        
        botMap.put("debug", debugCheckBox.isSelected());
        botMap.put("BOT_DELAY", botdelaySpinner.getValue());
        botMap.put("interval_ticker_update", intervaltickerupdateSpinner.getValue());
        botMap.put("period_storage_ticker", periodstoragetickerSpinner.getValue());
        botMap.put("timeout_buy", timeoutbuySpinner.getValue());
        botMap.put("timeout_sell", timeoutsellSpinner.getValue());
        botMap.put("TV_GAIN", tvgainSpinner.getValue());
        botMap.put("TV_TRADING_LIMIT_BUY", tvtradinglimitbuySpinner.getValue());
        botMap.put("TV_PYRAMID", tvpyramidCheckBox.isSelected());
        botMap.put("TV_TRADING_LIMIT_SELL", tvtradinglimitsellSpinner.getValue());
        botMap.put("TV_PROTECTION", tvprotectionCheckBox.isSelected());
        botMap.put("RETRY_TV_ORDER", retrytvorderCheckBox.isSelected());
        botMap.put("VERBOSE", verboseCheckBox.isSelected());
        botMap.put("WATCH_MODE", watchmodeCheckBox.isSelected());
        
        return botMap;
    }
    
    public void setMap_bot(LinkedTreeMap<String, Object> botMap) {
        if(botMap.containsKey("debug")) {
            debugCheckBox.setSelected((boolean)botMap.get("debug"));
        }
        if(botMap.containsKey("BOT_DELAY")) {
            botdelaySpinner.setValue(botMap.get("BOT_DELAY"));
        }
        if(botMap.containsKey("interval_ticker_update")) {
            intervaltickerupdateSpinner.setValue(botMap.get("interval_ticker_update"));
        }
        if(botMap.containsKey("period_storage_ticker")) {
            periodstoragetickerSpinner.setValue(botMap.get("period_storage_ticker"));
        }
        if(botMap.containsKey("timeout_buy")) {
            timeoutbuySpinner.setValue(botMap.get("timeout_buy"));
        }
        if(botMap.containsKey("timeout_sell")) {
            timeoutsellSpinner.setValue(botMap.get("timeout_sell"));
        }
        if(botMap.containsKey("TV_GAIN")) {
            tvgainSpinner.setValue(botMap.get("TV_GAIN"));
        }
        if(botMap.containsKey("TV_TRADING_LIMIT_BUY")) {
            tvtradinglimitbuySpinner.setValue(botMap.get("TV_TRADING_LIMIT_BUY"));
        }
        if(botMap.containsKey("TV_PYRAMID")) {
            tvpyramidCheckBox.setSelected((boolean)botMap.get("TV_PYRAMID"));
        }
        if(botMap.containsKey("TV_TRADING_LIMIT_SELL")) {
            tvtradinglimitsellSpinner.setValue(botMap.get("TV_TRADING_LIMIT_SELL"));
        }
        if(botMap.containsKey("TV_PROTECTION")) {
            tvprotectionCheckBox.setSelected((boolean)botMap.get("TV_PROTECTION"));
        }
        if(botMap.containsKey("RETRY_TV_ORDER")) {
            retrytvorderCheckBox.setSelected((boolean)botMap.get("RETRY_TV_ORDER"));
        }
        if(botMap.containsKey("VERBOSE")) {
            verboseCheckBox.setSelected((boolean)botMap.get("VERBOSE"));
        }
        if(botMap.containsKey("WATCH_MODE")) {
            watchmodeCheckBox.setSelected((boolean)botMap.get("WATCH_MODE"));
        }
    }
    
    public HashMap<String, Object> getMap_exchanges() {
        HashMap<String, Object> exchangesMap = new HashMap<>();
        
        HashMap<String, Object> bittrexMap = new HashMap<>();
        bittrexMap.put("key", exchangesTable.getValueAt(0, 1));
        bittrexMap.put("secret", exchangesTable.getValueAt(0, 2));
        exchangesMap.put("bittrex", bittrexMap);
        
        HashMap<String, Object> cryptopiaMap = new HashMap<>();
        cryptopiaMap.put("key", exchangesTable.getValueAt(1, 1));
        cryptopiaMap.put("secret", exchangesTable.getValueAt(1, 2));
        exchangesMap.put("cryptopia", cryptopiaMap);
        
        HashMap<String, Object> krakenMap = new HashMap<>();
        krakenMap.put("key", exchangesTable.getValueAt(2, 1));
        krakenMap.put("secret", exchangesTable.getValueAt(2, 2));
        exchangesMap.put("kraken", krakenMap);
        
        HashMap<String, Object> poloniexMap = new HashMap<>();
        poloniexMap.put("key", exchangesTable.getValueAt(3, 1));
        poloniexMap.put("secret", exchangesTable.getValueAt(3, 2));
        exchangesMap.put("poloniex", poloniexMap);
        
        return exchangesMap;
    }
    
    public void setMap_exchanges(LinkedTreeMap<String, Object> exchangesMap) {
        if (exchangesMap.containsKey("bittrex")) {
            LinkedTreeMap<String, Object> bittrexMap = (LinkedTreeMap<String, Object>)exchangesMap.get("bittrex");
            exchangesTable.setValueAt(bittrexMap.get("key"), 0, 1);
            exchangesTable.setValueAt(bittrexMap.get("secret"), 0, 2);
        }
        if (exchangesMap.containsKey("cryptopia")) {
            LinkedTreeMap<String, Object> cryptopiaMap = (LinkedTreeMap<String, Object>)exchangesMap.get("cryptopia");
            exchangesTable.setValueAt(cryptopiaMap.get("key"), 1, 1);
            exchangesTable.setValueAt(cryptopiaMap.get("secret"), 1, 2);
        }
        if (exchangesMap.containsKey("kraken")) {
            LinkedTreeMap<String, Object> krakenMap = (LinkedTreeMap<String, Object>)exchangesMap.get("kraken");
            exchangesTable.setValueAt(krakenMap.get("key"), 2, 1);
            exchangesTable.setValueAt(krakenMap.get("secret"), 2, 2);
        }
        if (exchangesMap.containsKey("poloniex")) {
            LinkedTreeMap<String, Object> poloniexMap = (LinkedTreeMap<String, Object>)exchangesMap.get("poloniex");
            exchangesTable.setValueAt(poloniexMap.get("key"), 0, 1);
            exchangesTable.setValueAt(poloniexMap.get("secret"), 0, 2);
        }
    }
    
    public HashMap<String, Object> getMap_pairs() {
        javax.swing.tree.TreeNode root = (javax.swing.tree.TreeNode)pairsTree.getModel().getRoot();
        HashMap<String, Object> pairsMap = parseMap(root);
        return pairsMap;
    }
    
    public void setMap_pairs(LinkedTreeMap<String, Object> pairsMap) {
        DefaultTreeModel model = (DefaultTreeModel)pairsTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        Set<String> keys = pairsMap.keySet();
        for (String key : keys) {
            DefaultMutableTreeNode childNode;
            childNode = parseNode((LinkedTreeMap<String, Object>) pairsMap.get(key), key);
            root.add(childNode);
        }
        model.reload(root);
        pairsTree.setVisible(false);
        pairsTree.setVisible(true);
    }
    
    public DefaultMutableTreeNode parseNode(LinkedTreeMap<String, Object> map, String label) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(label);
        Set<String> keys = map.keySet();
        for(String key : keys) {
            DefaultMutableTreeNode childNode;
            try {
                childNode = parseNode((LinkedTreeMap<String, Object>) map.get(key), key);
            }
            catch(Exception e) {
                childNode = new DefaultMutableTreeNode(key + ":" + (String)map.get(key));
            }
            node.add(childNode);
        }
        return node;
    }
    
    private HashMap<String, Object> parseMap(javax.swing.tree.TreeNode node) {
        HashMap<String, Object> nodeMap = new HashMap<>();
        
        int nCount = node.getChildCount();
        
        for (int i = 0; i < nCount ;i ++) {
            javax.swing.tree.TreeNode child = node.getChildAt(i);
            if (child.isLeaf()) {
                String strLeaf = child.toString();
                int seperator = strLeaf.indexOf(':');
                if (seperator == -1) {
                    continue;
                }
                else {
                    String strKey = strLeaf.substring(0, seperator).trim();
                    String strValue = strLeaf.substring(seperator);
                    nodeMap.put(strKey, strValue);
                }
            }
            else {
                String strKey = child.toString();
                HashMap<String, Object> mapValue = parseMap(child);
                nodeMap.put(strKey, mapValue);
            }
        }
        
        return nodeMap;
    }
    
    public HashMap<String, Object> getMap_imap_listener() {
        HashMap<String, Object> imap_listenerMap = new HashMap<>();
        
        imap_listenerMap.put("enabled", enabledCheckBox.isSelected());
        imap_listenerMap.put("authorized_froms", authorizedfromsTextField.getText());
        imap_listenerMap.put("user", userTextField.getText());
        imap_listenerMap.put("password", passwordTextField.getText());
        imap_listenerMap.put("host", hostTextField.getText());
        imap_listenerMap.put("port", port_imaglistenerSpinner.getValue());
        imap_listenerMap.put("tls", tlsCheckBox.isSelected());
        if(tlsCheckBox.isSelected()) {
            HashMap<String, Object> tlsOptionsMap = new HashMap<>();
            tlsOptionsMap.put("rejectUnauthorized", rejectunauthorizedCheckBox.isSelected());
            imap_listenerMap.put("tlsOptions", tlsOptionsMap);
        }
        
        return imap_listenerMap;
    }
    
    public void setMap_imap_listener(LinkedTreeMap<String, Object> imap_listenerMap) {
        enabledCheckBox.setSelected((boolean)imap_listenerMap.get("enabled"));
        authorizedfromsTextField.setText((String)imap_listenerMap.get("authorized_froms"));
        userTextField.setText((String)imap_listenerMap.get("user"));
        passwordTextField.setText((String)imap_listenerMap.get("password"));
        hostTextField.setText((String)imap_listenerMap.get("host"));
        port_imaglistenerSpinner.setValue(imap_listenerMap.get("port"));
        tlsCheckBox.setSelected((boolean)(imap_listenerMap.get("tls")));
        LinkedTreeMap<String, Object> tlsOptionsMap = (LinkedTreeMap<String, Object>)imap_listenerMap.get("tlsOptions");
        rejectunauthorizedCheckBox.setSelected((boolean)tlsOptionsMap.get("rejectUnauthorized"));
    }
    
    public HashMap<String, Object> getMap_strategies() {
        HashMap<String, Object> strategiesMap = new HashMap<>();
        
        int nCount = strategiesTable.getRowCount();
        for(int i = 0; i < nCount; i ++) {
            HashMap<String, Object> itemMap = new HashMap<>();
            itemMap.put("TRADING_LIMIT", strategiesTable.getValueAt(i, 1));
            itemMap.put("PERIOD", strategiesTable.getValueAt(i, 2));
            itemMap.put("BUY_LEVEL", strategiesTable.getValueAt(i, 3));
            itemMap.put("GAIN", strategiesTable.getValueAt(i, 4));
            itemMap.put("EMA1", strategiesTable.getValueAt(i, 5));
            itemMap.put("EMA2", strategiesTable.getValueAt(i, 6));
            itemMap.put("HIGH_BB", strategiesTable.getValueAt(i, 7));
            itemMap.put("LOW_BB", strategiesTable.getValueAt(i, 8));
            itemMap.put("STDV", strategiesTable.getValueAt(i, 9));
            itemMap.put("SMAPERIOD", strategiesTable.getValueAt(i, 10));
            itemMap.put("BUYLVL1", strategiesTable.getValueAt(i, 11));
            itemMap.put("BUYLVL2", strategiesTable.getValueAt(i, 12));
            itemMap.put("BUYLVL3", strategiesTable.getValueAt(i, 13));
            itemMap.put("SELLLVL1", strategiesTable.getValueAt(i, 14));
            itemMap.put("SELLLVL2", strategiesTable.getValueAt(i, 15));
            itemMap.put("SELLLVL3", strategiesTable.getValueAt(i, 16));
            itemMap.put("BUYLVL", strategiesTable.getValueAt(i, 17));
            itemMap.put("SELLLVL", strategiesTable.getValueAt(i, 18));
            itemMap.put("LASTPOINTS", strategiesTable.getValueAt(i, 19));
            itemMap.put("AVGPOINTS", strategiesTable.getValueAt(i, 20));
            itemMap.put("AVGMINIMUM", strategiesTable.getValueAt(i, 21));
            itemMap.put("PP_BUY", strategiesTable.getValueAt(i, 22));
            itemMap.put("PP_SELL", strategiesTable.getValueAt(i, 23));
            itemMap.put("PANIC_SELL", strategiesTable.getValueAt(i, 24));
            itemMap.put("DOUBLE_UP", strategiesTable.getValueAt(i, 25));
            itemMap.put("STOP_LIMIT", strategiesTable.getValueAt(i, 26));
            itemMap.put("BUY_ENABLED", strategiesTable.getValueAt(i, 27));
            itemMap.put("MIN_VOLUME_TO_BUY", strategiesTable.getValueAt(i, 28));
            itemMap.put("MIN_VOLUME_TO_SELL", strategiesTable.getValueAt(i, 29));
            String strName = (String)strategiesTable.getValueAt(i, 0);
            strategiesMap.put(strName, itemMap);
        }
        
        return strategiesMap;
    }
    
    public void setMap_strategies(LinkedTreeMap<String, Object> strategiesMap) {
        strategiesTable.removeAll();
        int i = 0;
        Set<String> names = strategiesMap.keySet();
        DefaultTableModel model = (DefaultTableModel)strategiesTable.getModel();
        model.setRowCount(names.size());
        for (String name : names) {
            strategiesTable.setValueAt(name, i, 0);
            LinkedTreeMap<String, Object> rowMap = (LinkedTreeMap<String, Object>)strategiesMap.get(name);
            strategiesTable.setValueAt(rowMap.get("TRADING_LIMIT"), i, 1);
            strategiesTable.setValueAt(rowMap.get("PERIOD"), i, 2);
            strategiesTable.setValueAt(rowMap.get("BUY_LEVEL"), i, 3);
            strategiesTable.setValueAt(rowMap.get("GAIN"), i, 4);
            strategiesTable.setValueAt(rowMap.get("EMA1"), i, 5);
            strategiesTable.setValueAt(rowMap.get("EMA2"), i, 6);
            strategiesTable.setValueAt(rowMap.get("HIGH_BB"), i, 7);
            strategiesTable.setValueAt(rowMap.get("LOW_BB"), i, 8);
            strategiesTable.setValueAt(rowMap.get("STDV"), i, 9);
            strategiesTable.setValueAt(rowMap.get("SMAPERIOD"), i, 10);
            strategiesTable.setValueAt(rowMap.get("BUYLVL1"), i, 11);
            strategiesTable.setValueAt(rowMap.get("BUYLVL2"), i, 12);
            strategiesTable.setValueAt(rowMap.get("BUYLVL3"), i, 13);
            strategiesTable.setValueAt(rowMap.get("SELLLVL1"), i, 14);
            strategiesTable.setValueAt(rowMap.get("SELLLVL2"), i, 15);
            strategiesTable.setValueAt(rowMap.get("SELLLVL3"), i, 16);
            strategiesTable.setValueAt(rowMap.get("BUYLVL"), i, 17);
            strategiesTable.setValueAt(rowMap.get("SELLLVL"), i, 18);
            strategiesTable.setValueAt(rowMap.get("LASTPOINTS"), i, 19);
            strategiesTable.setValueAt(rowMap.get("AVGPOINTS"), i, 20);
            strategiesTable.setValueAt(rowMap.get("AVGMINIMUM"), i, 21);
            strategiesTable.setValueAt(rowMap.get("PP_BUY"), i, 22);
            strategiesTable.setValueAt(rowMap.get("PP_SELL"), i, 23);
            strategiesTable.setValueAt(rowMap.get("PANIC_SELL"), i, 24);
            strategiesTable.setValueAt(rowMap.get("DOUBLE_UP"), i, 25);
            strategiesTable.setValueAt(rowMap.get("STOP_LIMIT"), i, 26);
            strategiesTable.setValueAt(rowMap.get("BUY_ENABLED"), i, 27);
            strategiesTable.setValueAt(rowMap.get("MIN_VOLUME_TO_BUY"), i, 28);
            strategiesTable.setValueAt(rowMap.get("MIN_VOLUME_TO_SELL"), i, 29);
            i ++;
        }
    }
    
    public HashMap<String, Object> getMap_optioanal() {
        HashMap<String, Object> optionalMap = new HashMap<>();
        
        HashMap<String, Object> toOverrideMap = new HashMap<>();
        
        double bought_price;
        try {
            bought_price = Integer.parseInt(boughtpriceTextField.getText());
        }
        catch(Exception e) {
            bought_price = 0;
        }
        
        toOverrideMap.put("BOUGHT_PRICE", bought_price);
        optionalMap.put("toOverride", toOverrideMap);
        
        return optionalMap;
    }
    
    public void setMap_optionals(LinkedTreeMap<String, Object> optionalsMap) {
        LinkedTreeMap<String, Object> toOverrideMap = (LinkedTreeMap<String, Object>)optionalsMap.get("toOverride");
        boughtpriceTextField.setText(String.valueOf(toOverrideMap.get("BOUGHT_PRICE")));
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    
    private HashMap<String, Object> readJSON(String jsonString) {
        Gson gsonObj = new Gson();
        java.lang.reflect.Type type = new TypeToken<HashMap<String, Object>>(){}.getType();
        HashMap<String, Object> hashMap = gsonObj.fromJson(jsonString, type);
        return hashMap;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorizedfromsTextField;
    private javax.swing.JSpinner botdelaySpinner;
    private javax.swing.JTextField boughtpriceTextField;
    private javax.swing.JSpinner clientportSpinner;
    private javax.swing.JCheckBox debugCheckBox;
    private javax.swing.JCheckBox enabledCheckBox;
    private javax.swing.JTable exchangesTable;
    private javax.swing.JTextField hostTextField;
    private javax.swing.JTextField hostnameTextField;
    private javax.swing.JSpinner intervaltickerupdateSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree pairsTree;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JSpinner periodstoragetickerSpinner;
    private javax.swing.JSpinner port_imaglistenerSpinner;
    private javax.swing.JSpinner port_wsSpinner;
    private javax.swing.JCheckBox rejectunauthorizedCheckBox;
    private javax.swing.JCheckBox retrytvorderCheckBox;
    private javax.swing.JTable strategiesTable;
    private javax.swing.JSpinner timeoutbuySpinner;
    private javax.swing.JSpinner timeoutsellSpinner;
    private javax.swing.JCheckBox tlsCheckBox;
    private javax.swing.JSpinner tvgainSpinner;
    private javax.swing.JCheckBox tvprotectionCheckBox;
    private javax.swing.JCheckBox tvpyramidCheckBox;
    private javax.swing.JSpinner tvtradinglimitbuySpinner;
    private javax.swing.JSpinner tvtradinglimitsellSpinner;
    private javax.swing.JTextField userTextField;
    private javax.swing.JCheckBox verboseCheckBox;
    private javax.swing.JCheckBox watchmodeCheckBox;
    // End of variables declaration//GEN-END:variables
}
